onaio/kujaku

library/src/main/AndroidManifest.xml, library/src/main/java/io/ona/kujaku/activities/MapActivity.java, library/src/main/java/io/ona/kujaku/helpers/MapBoxStyleStorage.java, library/src/main/java/io/ona/kujaku/helpers/converters/GeoJSONFeature.java, library/src/main/java/io/ona/kujaku/utils/Permissions.java, library/src/test/java/io/ona/kujaku/helpers/MapBoxStyleStorageTest.java, sample/src/main/res/values/strings.xml
=> Render mapbox style to map

library/build.gradle, utils/build.gradle
1. Add script to generate sources jar file
2. Add sources jar file as an artifact
3. Add sources jar as a MavenPublication artfact next to aar
=> Publish package together with sources

library/build.gradle, library/src/main/java/io/ona/kujaku/downloaders/MapBoxOfflineResourcesDownloader.java, library/src/main/java/io/ona/kujaku/listeners/IncompleteMapDownloadCallback.java, library/src/main/java/io/ona/kujaku/listeners/OnDownloadMapListener.java, library/src/main/java/io/ona/kujaku/listeners/OnPauseMapDownloadCallback.java, library/src/main/java/io/ona/kujaku/services/MapboxOfflineDownloaderService.java, library/src/main/java/io/ona/kujaku/utils/NumberFormatter.java
1. Exposed Broadcast message bundle keys in the MapBoxOfflineDownloaderService
2. Document MapBoxOfflineDownloaderService & MapBoxOfflineResourcesDownloader class
3. Code cleanup
4. Move number format utils from the Service to it's own class
=> Expose OfflineMapDownloadService Constants & Add OfflineMapDownloadService documentation

library/build.gradle, utils/build.gradle
Update the Kujaku library and utils packages to 0.2.0. Up from 0.1.3.
Signed-off-by: Jason Rogena <jasonrogena@gmail.com>
=> Library & Utlis v0.2.0

.travis.yml, library/build.gradle, sample/build.gradle, sample/src/test/java/io/ona/kujaku/sample/activities/MainActivityTest.java, utils/build.gradle, wrapper/build.gradle, wrapper/src/main/res/layout/activity_offline_map_downloder.xml
1. Disable lint abortOnError
2. Set default MAPBOX_ACCESS_TOKEN for travis
3. Add gradle build command
4. Add google repositories for support & other libraries
5. Remove Constraint Layout
6. Fix failing test
=>  Fix travis build

library/build.gradle, library/src/main/java/io/ona/kujaku/activities/MapActivity.java, sample/src/main/java/io/ona/kujaku/sample/activities/MainActivity.java, utils/build.gradle, utils/src/main/java/utils/Constants.java, utils/src/main/java/utils/helpers/MapBoxStyleHelper.java, utils/src/test/java/io/ona/kujaku/helpers/MapBoxStyleHelperTest.java
=> Deprecate parcelable top-left bound, bottom-right bounds & camera target

library/build.gradle, library/src/main/java/io/ona/kujaku/activities/MapActivity.java, sample/src/main/java/io/ona/kujaku/sample/activities/MainActivity.java, utils/build.gradle, utils/src/main/java/utils/Constants.java
=> Deprecate parcelable camera bearing

library/build.gradle, library/src/main/java/io/ona/kujaku/activities/MapActivity.java, library/src/main/res/layout/activity_map.xml, sample/src/main/java/io/ona/kujaku/sample/activities/MainActivity.java, utils/build.gradle, utils/src/main/java/utils/Constants.java, utils/src/main/java/utils/helpers/MapBoxStyleHelper.java, utils/src/test/java/io/ona/kujaku/helpers/MapBoxStyleHelperTest.java
Fixes #55
Fix my-location widget not clickable when Info Window comes up
=> Deprecate Parcelable ZOOM passed to MapActivity

library/build.gradle, library/src/main/java/io/ona/kujaku/activities/MapActivity.java
Focus on user location if the property is not set
Fixes #79
=> MapActivity should center to user position if center property has not been set in the MapBox Style

library/build.gradle, library/src/main/java/io/ona/kujaku/activities/MapActivity.java, sample/src/main/java/io/ona/kujaku/sample/activities/MainActivity.java, utils/build.gradle, utils/src/main/java/utils/Constants.java
=> Deprecate parcelable camera tilt passed to MapActivity

library/src/androidTest/java/io/ona/kujaku/data/realm/RealmDatabaseTest.java, library/src/main/java/io/ona/kujaku/data/realm/RealmDatabase.java, library/src/main/java/io/ona/kujaku/services/MapboxOfflineDownloaderService.java, sample/src/main/java/io/ona/kujaku/sample/activities/MainActivity.java
Closes #50 
Moves the remaining database operation to RealmDatabase class
=> Decongest MapboxOfflineDownloaderService

library/build.gradle, utils/build.gradle, utils/src/main/java/io/ona/kujaku/utils/helpers/MapBoxStyleHelper.java
This enables for one to activate focus-on-user-location feature on the MapActivity
Fixes #87
=> Remove center property from MapboxStyle

library/build.gradle, sample/build.gradle, utils/build.gradle, wrapper/build.gradle
Update the publishing details and Maven URLs from jasonrogena's to Ona's
Official Bintray account.
Fixes #31
Signed-off-by: Jason Rogena <jasonrogena@gmail.com>
=> Switch To Ona's Bintray Account

.travis.yml, README.md, build.gradle, gradle/wrapper/gradle-wrapper.properties, library/build.gradle, library/src/main/java/io/ona/kujaku/activities/MapActivity.java, library/src/test/java/io/ona/kujaku/notifications/DownloadProgressNotificationTest.java, library/src/test/java/io/ona/kujaku/notifications/KujakuNotificationImplClass2.java, library/src/test/java/io/ona/kujaku/notifications/KujakuNotificationTest.java, library/src/test/java/io/ona/kujaku/services/MapboxOfflineDownloaderServiceTest.java, sample/build.gradle, utils/build.gradle, utils/src/main/java/io/ona/kujaku/utils/config/DataSourceConfig.java, utils/src/main/java/io/ona/kujaku/utils/config/InfoWindowConfig.java, utils/src/main/java/io/ona/kujaku/utils/config/SortFieldConfig.java, utils/src/main/java/io/ona/kujaku/utils/helpers/MapBoxStyleHelper.java, utils/src/test/java/io/ona/kujaku/helpers/converters/GeoJSONHelperTest.java, wrapper/build.gradle
This also means that the gradle version and android gradle plugin were updated
=> Update mapbox SDK version to 6.5.0 from 5.2.0

library/build.gradle, utils/build.gradle
- Change the version of the library and utils to 0.3.0 due to change in the Mapbox SDK to 6.5.0
=> Increment version to 0.3.0

library/src/main/java/io/ona/kujaku/interfaces/IKujakuMapView.java, library/src/main/java/io/ona/kujaku/views/KujakuMapView.java, library/src/main/res/layout/activity_map.xml, library/src/main/res/layout/mapbox_mapview_internal.xml, library/src/main/res/values/attrs.xml, library/src/main/res/values/strings.xml, sample/build.gradle, sample/src/main/java/io/ona/kujaku/sample/activities/HighLevelMapView.java, sample/src/main/java/io/ona/kujaku/sample/activities/LowLevelLocationAddPointMapView.java, sample/src/main/java/io/ona/kujaku/sample/activities/LowLevelManualAddPointMapView.java, sample/src/main/res/layout/activity_low_level_manual_add_point_map_view.xml, sample/src/main/res/values/strings.xml
- Hide Current Location button by default
- Extract style attributes from the  KujakuMapView xml layout
- Add toast message to done button
=> Add toast message to done button and other changes

library/src/main/res/layout/mapbox_mapview_internal.xml, sample/src/main/AndroidManifest.xml, sample/src/main/java/io/ona/kujaku/sample/activities/BaseNavigationDrawerActivity.java, sample/src/main/java/io/ona/kujaku/sample/activities/HighLevelMapView.java, sample/src/main/java/io/ona/kujaku/sample/activities/LowLevelLocationAddPointMapView.java, sample/src/main/java/io/ona/kujaku/sample/activities/LowLevelManualAddPointMapView.java, sample/src/main/java/io/ona/kujaku/sample/activities/MainActivity.java, sample/src/main/res/drawable/ic_menu.xml, sample/src/main/res/layout/activity_high_level_map_view.xml, sample/src/main/res/layout/activity_low_level_location_add_point_map_view.xml, sample/src/main/res/layout/activity_low_level_manual_add_point_map_view.xml
1. Add a hamberger icon to be used as home
2. Use the BaseNavigationDrawerActivity for other activities
3. Fix navigation items selection on BaseNavigationDrawerActivity
4. Add noActionBar theme on all activities extending the BaseNavigationActivity
=> Add navigation menu to all activities

library/src/main/java/io/ona/kujaku/interfaces/ILocationClient.java, library/src/main/java/io/ona/kujaku/location/clients/AndroidLocationClient.java, library/src/main/java/io/ona/kujaku/location/clients/BaseLocationClient.java, library/src/main/java/io/ona/kujaku/location/clients/GPSLocationClient.java, library/src/main/java/io/ona/kujaku/views/KujakuMapView.java
This implements the GPS provider
=> Implement GPS Provider

library/src/main/java/io/ona/kujaku/views/KujakuMapView.java, sample/src/main/java/io/ona/kujaku/sample/activities/OfflineRegionsActivity.java, sample/src/main/java/io/ona/kujaku/sample/activities/TaskQueueActivity.java, sample/src/main/res/layout/nav_header_navigation_drawer.xml, sample/src/main/res/values/strings.xml
Some cleanup to remove the blank page notion
=> Show messages if there are no tasks or offline regions

library/src/main/java/io/ona/kujaku/activities/MapActivity.java, library/src/main/java/io/ona/kujaku/views/KujakuMapView.java, library/src/main/res/layout/item_info_window.xml, library/src/main/res/layout/view_info_window.xml, library/src/main/res/values/dimens.xml, sample/src/main/assets/sample-point-file.json, sample/src/main/java/io/ona/kujaku/sample/activities/MainActivity.java, wrapper/src/main/AndroidManifest.xml
=> Add mspray style and fix style

library/src/main/java/io/ona/kujaku/views/KujakuMapView.java, library/src/main/res/drawable/cancel_btn_bg.xml, library/src/main/res/drawable/circle_button_black_border.xml, library/src/main/res/drawable/ic_add.xml, library/src/main/res/layout/mapbox_mapview_internal.xml, library/src/main/res/values/strings.xml, sample/src/main/java/io/ona/kujaku/sample/activities/HighLevelLocationAddPointMapView.java, sample/src/main/java/io/ona/kujaku/sample/activities/LowLevelLocationAddPointMapView.java
1. Use a plus button for adding a new point
2. Show a done & cancel button after removing the plus button
3. Enable cancelling of add point
Fixes #145
=> Change add point UI/UX

README.md, library/build.gradle, utils/build.gradle
=> Fix broken artifact generation

.travis.yml, build.gradle, library/build.gradle, library/src/main/AndroidManifest.xml, library/src/main/java/io/ona/kujaku/utils/LocationPermissionListener.java, library/src/main/java/io/ona/kujaku/utils/LocationSettingsHelper.java, library/src/main/java/io/ona/kujaku/utils/Permissions.java, library/src/main/java/io/ona/kujaku/views/KujakuMapView.java, library/src/main/res/drawable/ic_my_location_focused.xml, library/src/main/res/values/strings.xml, library/src/test/java/io/ona/kujaku/BaseTest.java, library/src/test/java/io/ona/kujaku/notifications/BaseNotificationTest.java, library/src/test/java/io/ona/kujaku/test/shadows/ShadowGeoJsonSource.java, library/src/test/java/io/ona/kujaku/test/shadows/implementations/KujakuMapTestView.java, library/src/test/java/io/ona/kujaku/views/KujakuMapViewTest.java, sample/build.gradle, sample/src/main/AndroidManifest.xml, sample/src/main/java/io/ona/kujaku/sample/activities/HighLevelLocationAddPointMapView.java, sample/src/main/java/io/ona/kujaku/sample/activities/HighLevelMapView.java, sample/src/main/java/io/ona/kujaku/sample/activities/LowLevelLocationAddPointMapView.java, sample/src/main/java/io/ona/kujaku/sample/activities/LowLevelManualAddPointMapView.java, utils/build.gradle, utils/src/main/java/io/ona/kujaku/utils/Constants.java, wrapper/build.gradle
Supposed to fix the following issues:
- #164 
- #162 
- #165
- Make my location button bigger
Fixes #162 
Fixes #188
=> Fix recursive loop causing StackOverflow error, permission checks, tests, my location button size

library/build.gradle, sample/build.gradle, utils/build.gradle
This is to make the release for library and utils to 0.4.1
=> Increment library and utils version to 0.4.1

sample/src/main/AndroidManifest.xml, sample/src/main/assets/basic-feature-select-style.json, sample/src/main/java/io/ona/kujaku/sample/activities/BaseNavigationDrawerActivity.java, sample/src/main/java/io/ona/kujaku/sample/activities/FeatureClickStatusActivity.java, sample/src/main/res/layout/activity_feature_click_status.xml, sample/src/main/res/menu/activity_navigation_drawer_drawer.xml, sample/src/main/res/values/strings.xml
Related to #183 but not fixing it
- Go to the **Feature Click Status** activity from the Navigation menu
- Navigate to an area that you know has buildings or any polygonal feature, click on it, the feature should turn orange
- Clicking on another feature should also turn it to orange. This just enables you to select multiple features
=> Add sample activity showing how to add a feature select status

library/src/main/java/io/ona/kujaku/activities/MapViewLifecycleActivity.java, library/src/main/java/io/ona/kujaku/interfaces/IKujakuMapView.java, library/src/main/java/io/ona/kujaku/listeners/BoundsChangeListener.java, library/src/main/java/io/ona/kujaku/views/KujakuMapView.java, library/src/test/java/io/ona/kujaku/test/shadows/implementations/KujakuMapTestView.java, library/src/test/java/io/ona/kujaku/views/KujakuMapViewTest.java, sample/src/main/AndroidManifest.xml, sample/src/main/java/io/ona/kujaku/sample/activities/BaseNavigationDrawerActivity.java, sample/src/main/java/io/ona/kujaku/sample/activities/BoundingBoxListenerActivity.java, sample/src/main/java/io/ona/kujaku/sample/activities/BoundsChangeListenerActivity.java, sample/src/main/res/layout/activity_bounding_box_listener_activity.xml, sample/src/main/res/menu/activity_navigation_drawer_drawer.xml, sample/src/main/res/values/colors.xml, sample/src/main/res/values/strings.xml, sample/src/main/res/values/styles.xml
This fixes partly #155 
See #197 also
Fixes #203
=> Bounding box query support - Add bounding box changed listener

library/src/main/java/io/ona/kujaku/activities/MapActivity.java, library/src/main/java/io/ona/kujaku/downloaders/MapBoxOfflineResourcesDownloader.java, sample/build.gradle, sample/src/main/java/io/ona/kujaku/sample/activities/BaseNavigationDrawerActivity.java, sample/src/main/java/io/ona/kujaku/sample/activities/OfflineRegionsActivity.java
=> Fix bugs in the library and required cleanups on the sample app

library/build.gradle, sample/build.gradle, utils/build.gradle
This is to make the release for library and utils to 0.5.0
=> Increment library and utils version to 0.5.0

library/src/main/java/io/ona/kujaku/views/KujakuMapView.java, sample/src/main/AndroidManifest.xml, sample/src/main/java/io/ona/kujaku/sample/activities/BaseNavigationDrawerActivity.java, sample/src/main/java/io/ona/kujaku/sample/activities/BoundsAwareActivity.java, sample/src/main/java/io/ona/kujaku/sample/utils/TestDataUtils.java, sample/src/main/res/layout/activity_bounds_aware.xml, sample/src/main/res/layout/content_bounds_aware.xml, sample/src/main/res/menu/activity_navigation_drawer_drawer.xml, sample/src/main/res/values/strings.xml
=> Demonstrate adding points to MapView OnBoundsChange

library/src/main/java/io/ona/kujaku/helpers/OfflineServiceHelper.java, library/src/main/java/io/ona/kujaku/services/MapboxOfflineDownloaderService.java, library/src/main/res/values/strings.xml, sample/src/main/java/io/ona/kujaku/sample/activities/MainActivity.java, sample/src/main/res/layout/content_main_activity.xml, sample/src/main/res/values/strings.xml
=> Add Offline map download helper

README.md, SPECIFICATION.md, sample/README.md, sample_mapbox_style_with_kujaku_config.json
=> Add specification for 'Add point' feature

library/src/main/java/io/ona/kujaku/exceptions/AsyncTaskCancelledException.java, library/src/main/java/io/ona/kujaku/tasks/GenericAsyncTask.java
=> Fix generic asynctask to carry over exceptions thrown in doInBackground

library/src/main/java/io/ona/kujaku/interfaces/IKujakuMapView.java, library/src/main/java/io/ona/kujaku/utils/LocationSettingsHelper.java, library/src/main/java/io/ona/kujaku/views/KujakuMapView.java, library/src/main/res/values/attrs.xml, library/src/main/res/values/strings.xml, sample/src/main/res/layout/activity_low_level_manual_add_point_map_view.xml
1. Add isWarmGPS() and setWarmGps(boolean) API to IKujakuMapView
2. Add mapbox_warmGps property to KujakuMapView xml so that warming can be disabled in the styling xml
3. Make warming GPS enabled by default
Todo:
=> Make warming GPS configurable/optional

library/build.gradle, library/src/main/java/io/ona/kujaku/location/clients/AndroidLocationClient.java
- Remove deprecated FuseLocationApi and use the new FusedLocationProviderClient
Fixes #198
=> Update google play location service version to 16.0.0

README.md
=> Add artifact version badge & link to license file

library/src/main/java/io/ona/kujaku/activities/MapActivity.java, sample/src/main/assets/sample-point-file.json
=> Fix bug associated adding an geojson source url

.gitignore, .travis.yml, README.md, build.gradle, library/build.gradle, library/src/androidTest/java/io/ona/kujaku/downloaders/MapBoxOfflineResourcesDownloaderTest.java, library/src/main/java/io/ona/kujaku/views/KujakuMapView.java, sample/build.gradle, sample/src/androidTest/java/io/ona/kujaku/sample/ExampleInstrumentedTest.java~Fix instrumented tests, sample/src/androidTest/java/io/ona/kujaku/sample/ExampleInstrumentedTest.java~HEAD, utils/build.gradle, wrapper/build.gradle
Fixes #65
This PR depends on #228
=> Fix jacoco coverage & coveralls integration

library/build.gradle, library/src/androidTest/java/io/ona/kujaku/views/KujakuMapViewTest.java, library/src/main/java/io/ona/kujaku/callbacks/OnLocationComponentInitializedCallback.java, library/src/main/java/io/ona/kujaku/helpers/MapboxLocationComponentWrapper.java
This will make sure e.g. the LocationComponent default styling is fully loaded hence one can easily override it in the callback.
=> Add callback to be invoked after the LocationComponent is initialized

library/build.gradle, sample/build.gradle, utils/build.gradle
- enable artifact import in modules
- Increment library and utils version to 0.7.0
=> Increment library and utils version to 0.7.0

library/build.gradle, sample/build.gradle, sample/src/main/res/values/strings.xml
- Revert WMTS activity WMTS url to texas vegetation map
=> Create release 0.7.3

library/build.gradle, library/src/main/java/io/ona/kujaku/layers/ArrowLineLayer.java, library/src/test/java/io/ona/kujaku/layers/ArrowLineLayerTest.java, library/src/test/java/io/ona/kujaku/test/shadows/ShadowGeoJsonSource.java, sample/build.gradle, sample/src/main/AndroidManifest.xml, sample/src/main/assets/case-relationship-features.geojson, sample/src/main/java/io/ona/kujaku/sample/activities/BaseNavigationDrawerActivity.java, sample/src/main/java/io/ona/kujaku/sample/activities/OneToManyCaseRelationshipActivity.java, sample/src/main/java/io/ona/kujaku/sample/activities/OneToOneCaseRelationshipActivity.java, sample/src/main/res/layout/activity_case_relationship_activity.xml, sample/src/main/res/menu/activity_navigation_drawer_drawer.xml, sample/src/main/res/values/strings.xml
=> Enable one to many relationship for the arrow line. One-to-Many case relationship

library/src/main/java/io/ona/kujaku/activities/MapActivity.java, library/src/main/java/io/ona/kujaku/interfaces/IKujakuMapView.java, library/src/main/java/io/ona/kujaku/views/KujakuMapView.java, sample/build.gradle
=> Allow Toggle of my location

library/src/main/java/io/ona/kujaku/KujakuLibrary.java, library/src/main/java/io/ona/kujaku/layers/ArrowLineLayer.java, sample/README.md, sample/build.gradle, sample/src/main/AndroidManifest.xml, sample/src/main/assets/reveal-streets-satellite-style.json, sample/src/main/java/io/ona/kujaku/sample/MyApplication.java, sample/src/main/java/io/ona/kujaku/sample/activities/BaseNavigationDrawerActivity.java, sample/src/main/java/io/ona/kujaku/sample/activities/CGRIntegrationActivity.java, sample/src/main/res/layout/activity_cgr_integration_activity.xml, sample/src/main/res/layout/dialog_progress.xml, sample/src/main/res/menu/activity_navigation_drawer_drawer.xml, sample/src/main/res/values/strings.xml
=> Integrate cgr adapter

library/build.gradle, sample/build.gradle
- Increment library version
- Enable kujaku library release imports on the sample module
=> Increment library version to 0.7.7

library/build.gradle, sample/build.gradle
- Increment library version
- Enable kujaku library release imports on the sample module
=> Increment library version to 0.7.8

library/build.gradle, sample/build.gradle
- Increment library version
- Enable kujaku library release imports on the sample module
=> Increment library version to 0.7.9

library/build.gradle, sample/build.gradle, utils/build.gradle
=> Release 0.8.0

library/build.gradle, library/src/main/java/io/ona/kujaku/location/clients/AndroidGpsLocationClient.java, library/src/main/java/io/ona/kujaku/location/clients/GoogleLocationClient.java, library/src/main/java/io/ona/kujaku/views/KujakuMapView.java
=>  Remove GPS accuracy toast message

.github/workflows/ci.yml, .github/workflows/library.yml, .github/workflows/utils.yml, library/build.gradle, publish.gradle, utils/build.gradle
=> Add library and utils automatic publishing of SNAPSHOTS

README.md
- Update README.MD with instructions on how to publish artefacts for the utils and library modules
=> Add instructions on how to publish artefacts

.github/workflows/library.yml, configs.gradle, library/build.gradle, library/src/main/AndroidManifest.xml, library/src/main/java/io/ona/kujaku/helpers/PermissionsHelper.java, library/src/main/java/io/ona/kujaku/utils/KujakuMultiplePermissionListener.java, library/src/main/java/io/ona/kujaku/utils/Permissions.java, sample/.gitignore, sample/src/main/java/io/ona/kujaku/sample/activities/MainActivity.java
Related to https://github.com/opensrp/fhircore/issues/3431
=> Resolve permission location for higher android builds.
